# Generated by Django 4.1.7 on 2024-04-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('aviatickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='avaible_seats',
            field=models.IntegerField(default=100, verbose_name='Доступных мест'),
            preserve_default=False,
        ),
    ]
