# Generated by Django 4.1.7 on 2023-03-13 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_origin', models.CharField(max_length=100, verbose_name='Город вылета')),
                ('name_dest', models.CharField(max_length=100, verbose_name='Город прилета')),
                ('name_origin_aero', models.CharField(max_length=100, verbose_name='Аэропорт вылета')),
                ('name_dest_aero', models.CharField(max_length=100, verbose_name='Аэропорт прилета')),
                ('time_origin', models.TimeField(verbose_name='Время и дата вылета')),
                ('time_dest', models.TimeField(verbose_name='Время и дата прилета')),
                ('date_origin', models.DateField(verbose_name='Время прилета')),
                ('date_dest', models.DateField(verbose_name='Время прилета')),
                ('ticket_price', models.IntegerField(verbose_name='Цена билета')),
                ('type_of_flight', models.CharField(choices=[('Эконом', 'Эконом'), ('Бизнес', 'Бизнес'), ('Первый класс', 'Первый класс')], max_length=100, verbose_name='Тип перелета')),
            ],
        ),
        migrations.CreateModel(
            name='UsersSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tickets')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
