# Generated by Django 4.1.7 on 2023-03-14 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userssales_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userssales',
            old_name='sale',
            new_name='ticket',
        ),
    ]
